name: Build and Deploy Java Modules

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [allocations, base, deadlock, highcpu, hotmethods, latencies, memoryleak, memoryref, threadleak]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      # Step 3: Build the application
      - name: Build Maven Module
        run: |
          mvn clean package -pl ${{ matrix.module }} -am -DskipTests

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg module=${{ matrix.module }} \
            -t your-dockerhub-username/${{ matrix.module }} .

      # Step 5: Push Docker Image to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push your-dockerhub-username/${{ matrix.module }}
